# Generated by Django 5.0.6 on 2026-04-01 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('record_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('business', 'Business'), ('bonus', 'Bonus'), ('rental', 'Rental Income'), ('other_income', 'Other Income'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('housing', 'Housing & Rent'), ('insurance', 'Insurance'), ('tax', 'Tax'), ('other_expense', 'Other Expense')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['record_type'], name='financial_r_record__802acb_idx'), models.Index(fields=['category'], name='financial_r_categor_2871f2_idx'), models.Index(fields=['date'], name='financial_r_date_c7ef46_idx'), models.Index(fields=['is_deleted'], name='financial_r_is_dele_213f2d_idx')],
            },
        ),
    ]
